version: '3.1'

services:
  music-rest-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: iquee/music-rest-api:latest
    container_name: music-rest-api
    ports:
      - 8080:8080
    working_dir: /opt/app
    networks:
      - music
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - music
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - music
    
networks:
  music:
